openapi: 3.0.3
info:
  title: Library API
  version: 1.2.0
  description: STD22049
servers:
  - url: https://library.com
tags:
  - name: Books
    description: request about books
  - name: Authors
    description: request about authors
  - name: Visitors
    description: request about visitors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        #TODO3: add parameter to filter books by intervals of dates of the releaseDate
        - in: query
          name: releaseDateMin
          description: first parameter for the filtering
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: releaseDateMax
          description: second parameter for the filtering
          required: false
          schema:
            type: string
            format: date
        - $ref: '#/components/parameters/queryPagination'
      responses:
        200:
          $ref: '#/components/responses/successForBooks'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          $ref: '#/components/responses/successForBooks'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
    delete:
      tags:
        - Books
      summary: Delete a books
      description: Delete one /books/ with given id
      parameters:
        - name: id
          in: query
          description: given id for the delete operation
          required: true
          schema:
            type: integer
      responses:
          200:
            description: Deleted successfully
          400:
            $ref: '#/components/responses/badRequest'
          403:
            $ref: '#/components/responses/forbiddenError'
          500:
            $ref: '#components/responses/serverError'
  /books/import:
    post:
      tags:
        - Books
      summary: Import books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportBook'
          application/vnd.ms-excel:
            schema:
              $ref: '#/components/schemas/ImportBook'
      responses:
          200:
            $ref: '#/components/responses/successForBooks'
          400:
            $ref: '#/components/responses/badRequest'
          403:
            $ref: '#/components/responses/forbiddenError'
          500:
            $ref: '#components/responses/serverError'
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
        - name: authorId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/successForBooks'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
  /books/authors:
    put:
      tags:
        - Books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBookAuthor'
      responses:
        200:
          $ref: '#/components/responses/successForBooks'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'

  /authors/page_with_size/{pageAndSize}:
    get:
      tags:
        - Authors
      summary: Get the authors
      description: The list of all authors
      parameters:
        - $ref: '#/components/parameters/pathPagination'
      responses:
        200:
          $ref: '#/components/responses/successForAuthors'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
  /authors:
  #TODO2: complete GET (can be filtered by name) - PUT - DELETE
    get:
      tags:
        - Authors
      summary: Get the authors
      description: The list of all authors
      parameters:
        - name: authorName
          in: query
          description: Filter the author by given name
          required: false
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/successForAuthors'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
    put:
      tags:
        - Authors
      summary: Update author
      description: Update partially or totally the author's information
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/authors'
      responses:
        200:
          $ref: '#/components/responses/successForAuthors'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
    delete:
      tags:
        - Authors
      summary: Delete a author
      description: Delete one or many author with list of id
      parameters:
        - name: listOfId
          in: query
          description: given id for the delete operation
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        200:
          description: Deleted successfully
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
  /authors/import:
    post:
      tags:
        - Authors
      summary: Import authors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportAuthor'
          application/vnd.ms-excel:
            schema:
              $ref: '#/components/schemas/ImportAuthor'
      responses:
        200:
          $ref: '#/components/responses/successForAuthors'
        400:
          $ref: '#/components/responses/badRequest'
        403:
          $ref: '#/components/responses/forbiddenError'
        500:
          $ref: '#components/responses/serverError'
    
components:
  parameters:
    pathPagination:
      name: pageAndSize
      in: path
      required: true
      schema:
        type: string
        pattern: "^[0-9]+-[0-9]+$"
        default: "1-50"
    queryPagination:
      name: pageAndSize
      in: query
      required: false
      schema:
        type: string
        pattern: "^[0-9]+-[0-9]+$"
        default: "1-50"
  responses:
    successForBooks:
      description: OK!
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Book'
    successForAuthors:
      description: OK!
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/authors'
    badRequest:
      description: Bad request
    forbiddenError:
      description: Forbidden
    serverError:
      description: Internal server error
  schemas:
    authors:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
    CrupdateBook:
      type: object
      properties:
        id:
          type: integer
        bookName:
          type: string
        pageNumbers: 
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    Book:
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
        - type: object
      properties:
        author:
          $ref: "#/components/schemas/authors"
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: integer
      required:
        - bookId
        - authorId
    Visitors:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        reference:
          type: string
    DataBook:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
        idAuthor:
          type: integer
    DataAuthor:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string
    
    ImportBookJSON:
      allOf:
        - $ref: '#/components/schemas/DataBook'
    ImportBookExcel:
      allOf:
        - $ref: '#/components/schemas/DataBook'
    ImportAuthorJSON:
      allOf:
        - $ref: '#/components/schemas/DataAuthor'
    ImportAuthorExcel:
      allOf:
          - $ref: '#/components/schemas/DataAuthor'
    ImportAuthor:
      oneOf:
        - $ref: '#/components/schemas/ImportAuthorJSON'
        - $ref: '#/components/schemas/ImportAuthorExcel'
    ImportBook:
      oneOf:
        - $ref: '#/components/schemas/ImportBookJSON'
        - $ref: '#/components/schemas/ImportBookExcel'